language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t yusrawasi/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run yusrawasi/react-test npm test -- --coverage

after_success: #for production
  - docker build -t yusrawasi/multi-client ./client #not writing -f as using default dockerfilee that is Dockerfle(prod)
  - docker build -t yusrawasi/multi-nginx ./nginx
  - docker build -t yusrawasi/multi-server ./server
  - docker build -t yusrawasi/multi-worker ./worker 
#log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#take those images and push them to dockerhub
  - docker push yusrawasi/muti-client
  - docker push yusrawasi/muti-nginx
  - docker push yusrawasi/muti-server
  - docker push yusrawasi/muti-worker

